disabled_rules: # rule identifiers to exclude from running
#  - colon
  - comma
#  - control_statement
#  - file_length
  - force_cast # TODO
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
#  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
  - variable_name # e.g. TEST_TEST is not allowed
  - cyclomatic_complexity
  - valid_docs
#  - closing_brace
#  - conditional_binding_cascade
#  - custom_rules
  - function_parameter_count
#  - legacy_constant
#  - legacy_constructor

opt_in_rules:
#  - empty_count # TODO
#  - force_unwrapping # TODO
  - missing_docs

included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - Sources
  - UnitTests
  - UITests

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Vendor

line_length:
  warning: 200
  error: 250

file_length:
  - 1000

type_name:
  min_length:
    warning: 2

variable_name:
  min_length:
    warning: 2

function_body_length:
  warning: 200
  error: 400

type_body_length:
  warning: 420
  error: 500
